version: '3.8'

services:
  app_blue:
    build: ./getting-started-app
    ports:
      - "3001:3000"
    environment:
      - ENV_COLOR=blue
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  app_green:
    build: ./getting-started-app
    ports:
      - "3002:3000"
    environment:
      - ENV_COLOR=green
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  reverse_proxy:
    image: nginx
    ports:
      - "81:81"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_blue
      - app_green
